create table public.crm_pipelines (id uuid primary key default gen_random_uuid(),barbershop_id uuid not null references public.barbershops(id) on delete cascade,name text not null,active boolean not null default true,created_at timestamptz not null default now(),unique(barbershop_id,name),unique(barbershop_id,id));
create table public.crm_stages (id uuid primary key default gen_random_uuid(),barbershop_id uuid not null,pipeline_id uuid not null,name text not null,position smallint not null default 0,color text,created_at timestamptz not null default now(),foreign key(barbershop_id,pipeline_id) references public.crm_pipelines(barbershop_id,id) on delete cascade,unique(pipeline_id,name),unique(barbershop_id,id));
create table public.crm_opportunities (id uuid primary key default gen_random_uuid(),barbershop_id uuid not null,client_id uuid not null,stage_id uuid not null,title text not null,source text not null default 'manual',value numeric(12,2),next_action_at timestamptz,status text not null default 'open' check(status in ('open','won','lost','archived')),notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),foreign key(barbershop_id,client_id) references public.clients(barbershop_id,id),foreign key(barbershop_id,stage_id) references public.crm_stages(barbershop_id,id),unique(barbershop_id,id));
create table public.automation_rules (id uuid primary key default gen_random_uuid(),barbershop_id uuid not null references public.barbershops(id) on delete cascade,name text not null,trigger_type text not null check(trigger_type in ('birthday','return_due','appointment_created','appointment_reminder','appointment_completed','crm_stage_changed')),channel text not null default 'whatsapp' check(channel in ('whatsapp','email','internal')),delay_minutes integer not null default 0 check(delay_minutes>=0),template_body text not null,conditions jsonb not null default '{}'::jsonb,active boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(barbershop_id,name));
create table public.automation_runs (id uuid primary key default gen_random_uuid(),barbershop_id uuid not null references public.barbershops(id) on delete cascade,rule_id uuid references public.automation_rules(id) on delete set null,client_id uuid,deduplication_key text not null,status text not null default 'queued' check(status in ('queued','processing','sent','failed','cancelled')),scheduled_for timestamptz not null,started_at timestamptz,finished_at timestamptz,error_message text,payload jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),foreign key(barbershop_id,client_id) references public.clients(barbershop_id,id) on delete set null (client_id),unique(barbershop_id,deduplication_key),unique(barbershop_id,id));
create table public.whatsapp_connections (id uuid primary key default gen_random_uuid(),barbershop_id uuid not null unique references public.barbershops(id) on delete cascade,provider text not null default 'meta_cloud',phone_number_id text,business_account_id text,secret_reference text,status text not null default 'disconnected' check(status in ('disconnected','pending','connected','error')),verified_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.whatsapp_messages (id uuid primary key default gen_random_uuid(),barbershop_id uuid not null references public.barbershops(id) on delete cascade,client_id uuid,automation_run_id uuid,provider_message_id text,direction text not null check(direction in ('inbound','outbound')),template_name text,body_preview text,status text not null default 'queued' check(status in ('queued','sent','delivered','read','failed','received')),sent_at timestamptz,delivered_at timestamptz,read_at timestamptz,created_at timestamptz not null default now(),foreign key(barbershop_id,client_id) references public.clients(barbershop_id,id) on delete set null (client_id),foreign key(barbershop_id,automation_run_id) references public.automation_runs(barbershop_id,id) on delete set null (automation_run_id));
create table public.integration_events (id uuid primary key default gen_random_uuid(),barbershop_id uuid references public.barbershops(id) on delete cascade,source text not null,event_type text not null,external_id text,status text not null default 'received' check(status in ('received','processed','ignored','failed')),payload jsonb not null default '{}'::jsonb,error_message text,received_at timestamptz not null default now(),processed_at timestamptz,unique(source,external_id));

create index crm_opportunities_shop_stage_idx on public.crm_opportunities(barbershop_id,stage_id,status);
create index crm_opportunities_next_action_idx on public.crm_opportunities(barbershop_id,next_action_at) where status='open';
create index automation_runs_queue_idx on public.automation_runs(status,scheduled_for) where status='queued';
create index whatsapp_messages_shop_created_idx on public.whatsapp_messages(barbershop_id,created_at desc);
create index integration_events_status_idx on public.integration_events(status,received_at) where status in ('received','failed');

alter table public.crm_pipelines enable row level security; alter table public.crm_stages enable row level security; alter table public.crm_opportunities enable row level security; alter table public.automation_rules enable row level security; alter table public.automation_runs enable row level security; alter table public.whatsapp_connections enable row level security; alter table public.whatsapp_messages enable row level security; alter table public.integration_events enable row level security;
create policy crm_pipelines_tenant_all on public.crm_pipelines for all to authenticated using ((select private.is_tenant_member(barbershop_id))) with check ((select private.is_tenant_member(barbershop_id)));
create policy crm_stages_tenant_all on public.crm_stages for all to authenticated using ((select private.is_tenant_member(barbershop_id))) with check ((select private.is_tenant_member(barbershop_id)));
create policy crm_opportunities_tenant_all on public.crm_opportunities for all to authenticated using ((select private.is_tenant_member(barbershop_id))) with check ((select private.is_tenant_member(barbershop_id)));
create policy automation_rules_tenant_all on public.automation_rules for all to authenticated using ((select private.is_tenant_member(barbershop_id))) with check ((select private.is_tenant_member(barbershop_id)));
create policy automation_runs_tenant_read on public.automation_runs for select to authenticated using ((select private.is_tenant_member(barbershop_id)));
create policy whatsapp_connections_tenant_read on public.whatsapp_connections for select to authenticated using ((select private.is_tenant_member(barbershop_id)));
create policy whatsapp_messages_tenant_read on public.whatsapp_messages for select to authenticated using ((select private.is_tenant_member(barbershop_id)));
create policy integration_events_tenant_read on public.integration_events for select to authenticated using (barbershop_id is not null and (select private.is_tenant_member(barbershop_id)));
grant select,insert,update,delete on public.crm_pipelines,public.crm_stages,public.crm_opportunities,public.automation_rules to authenticated;
grant select on public.automation_runs,public.whatsapp_connections,public.whatsapp_messages,public.integration_events to authenticated;

insert into public.crm_pipelines(barbershop_id,name) select id,'Relacionamento' from public.barbershops on conflict do nothing;
insert into public.crm_stages(barbershop_id,pipeline_id,name,position,color) select p.barbershop_id,p.id,s.name,s.position,s.color from public.crm_pipelines p cross join (values('Novo contato',1,'#9caeff'),('Agendamento pendente',2,'#d8b7bd'),('Cliente ativo',3,'#72b88d'),('Reativação',4,'#e5a76f')) s(name,position,color) where p.name='Relacionamento' on conflict do nothing;
insert into public.automation_rules(barbershop_id,name,trigger_type,delay_minutes,template_body,active) select id,'Retorno de cliente','return_due',0,'Olá, {{cliente.nome}}! Já está na hora do seu próximo atendimento. Agende aqui: {{link_agendamento}}',false from public.barbershops on conflict do nothing;
insert into public.automation_rules(barbershop_id,name,trigger_type,delay_minutes,template_body,active) select id,'Aniversário','birthday',540,'Feliz aniversário, {{cliente.nome}}! {{empresa.nome}} deseja um dia especial para você.',false from public.barbershops on conflict do nothing;
